version: "1"
rules:
  - base: applemod
    upstream: SirPlease:master    # change `wei` to the owner of upstream repo
    mergeMethod: merge
  - base: master
    upstream: SirPlease:master    # change `wei` to the owner of upstream repo
    mergeMethod: merge
    
# You can manually trigger Pull by going to https://pull.git.ci/process/${owner}/${repo}.
